name: getx_clean_boiler_plate
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  collection: ^1.17.1
  dartz: ^0.10.1
  dynamic_color: ^1.6.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  get: ^4.6.5
  go_router: ^12.1.3
  http: ^1.1.0
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7

flutter:
  uses-material-design: true
